### ISSUE TITLE
Users are forgetful.

### ISSUE THREAD

**Issue by lwatterworth-cldr** [cegganesh84/cdp-azure-tools#1]
Hi!  

Great tool, I can see that numerous folks use this for prepping a small environment for testing within Azure.  

Unfortunately, many users forget to clean up the Azure RG after they've finished with it..  then just create another for their next test....    ..manowar-test subscription (among others?) are littered with abandoned resources created by this tool.

Hoping that you could consider a few changes to help:
- Add a reminder in the README
- correlate resource names with the user's userid.  
- stuff the users' userid /email/etc into tags
- prompt user for "destroy after" date for the RGs  (stuff this into a tag, too..)

thanks!

**Comment by cegganesh84** [comment]
@lwatterworth-cldr Thanks for the feedback. Added a new template for this, with a note about cleaning.
